name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject Cesium API Key into index.html
      env:
        CESIUM_API_KEY: ${{ secrets.CESIUMAPI }}
      run: |
        echo "Injecting Cesium API Key..."
        sed -i 's/<<CESIUM_API_KEY>>/'"$CESIUM_API_KEY"'/' index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: . # Adjust if using a build directory like `dist`
