name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject Cesium API Key into index.html
      env:
        CESIUM_API_KEY: ${{ secrets.CESIUMAPI }}
      run: |
        echo "Injecting Cesium API Key..."
        sed -i 's/<<CESIUM_API_KEY>>/'"$CESIUM_API_KEY"'/' index.html
        echo "Updated index.html contents:"
        cat index.html

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Inject Cesium API Key"
        git push
